# Generated by Django 5.0.4 on 2024-08-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0003_wearable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.BooleanField(blank=True, null=True)),
                ('footwear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footwear_set', to='closet.wearable')),
                ('pants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pants_set', to='closet.wearable')),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirt_set', to='closet.wearable')),
            ],
            options={
                'unique_together': {('shirt', 'pants', 'footwear')},
            },
        ),
    ]
