# Generated by Django 5.0.4 on 2024-05-07 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.closetuser')),
            ],
        ),
        migrations.CreateModel(
            name='Wearable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('s', 'SHIRT'), ('p', 'PANTS'), ('f', 'FOOTWEAR')], max_length=8)),
                ('usage_1', models.CharField(choices=[('f', 'FORMAL'), ('c', 'CASUAL'), ('s', 'SPORT'), ('g', 'GENERAL')], max_length=8)),
                ('usage_2', models.CharField(choices=[('f', 'FORMAL'), ('c', 'CASUAL'), ('s', 'SPORT'), ('g', 'GENERAL')], max_length=8)),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.closet')),
            ],
        ),
    ]
