# Generated by Django 5.0.4 on 2024-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearable',
            name='accessible',
            field=models.BooleanField(default=True),
        ),
    ]
