# Generated by Django 5.0.4 on 2024-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_wearable_accessible'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
