# Generated by Django 5.0.4 on 2024-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_wearable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearable',
            name='image',
        ),
        migrations.AddField(
            model_name='wearable',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
