# Generated by Django 5.0.4 on 2024-08-11 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_closetuser_groups_closetuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closetuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='closetuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='closetuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
